name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: ./gradlew test

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport

      - name: Enforce Coverage
        run: ./gradlew jacocoTestCoverageVerification

      - name: Sonar Scan
        run: |
          ./gradlew sonarqube \
            --warning-mode=all \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.qualitygate.wait=true \
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
            -Dsonar.pullrequest.branch=${{ github.head_ref }} \
            -Dsonar.pullrequest.base=${{ github.base_ref }}
